<a href="https://colab.research.google.com/github/Alisa7A/-/blob/main/%D0%9B%D0%B0%D0%B1_1_(%D0%A8%D0%B0%D0%BC%D1%96%D0%B3%D1%83%D0%BB%D0%BE%D0%B2%D0%BE%D1%97_%D0%90%D0%BB%D1%96%D1%81%D0%B8).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.__version__

'2.0.2'

1. Створити матрицю 3*3, заповни її цілими випадковими числами від 1 до 5

In [4]:
matrix = np.random.randint(1,6, size=(3,3))
matrix

array([[1, 2, 1],
       [2, 4, 4],
       [4, 2, 3]])

2. Обчислити визначник матриці

In [5]:
det = np.linalg.det(matrix)
det

np.float64(12.0)

3. Знайти добуток всіх елементів матриці

In [6]:
product = np.prod(matrix)
product

np.int64(1536)

In [7]:
prod_1 = np.prod(matrix[0])
prod_2 = np.prod(matrix[1])
prod_3 = np.prod(matrix[2])
prod_1*prod_2*prod_3

np.int64(1536)

4. Знайти суму всіх елементів матриці

In [8]:
sum = np.sum(matrix)
sum

np.int64(23)

5. Обчислити найбільший, найменший елементи

In [9]:
max_element = np.max(matrix)
print("Найбільший елемент матриці:", max_element)
min_element = np.min(matrix)
print("Найменший елемент матриці:", min_element)

Найбільший елемент матриці: 4
Найменший елемент матриці: 1


6. Знайти середнє значення елементів матриці

In [10]:
mean = np.mean(matrix)
print("Середнє значення елементів матриці:", mean)

Середнє значення елементів матриці: 2.5555555555555554


7. Знайти матрицю, що складена з квадратних коренів

In [11]:
sqrt_matrix = np.sqrt(matrix)
print("Матриця квадратних коренів:")
print(sqrt_matrix)

Матриця квадратних коренів:
[[1.         1.41421356 1.        ]
 [1.41421356 2.         2.        ]
 [2.         1.41421356 1.73205081]]


8. Обчислити суму елементів кожного рядка. Відповідь записати як вектор-стовпчик

In [12]:
row_sums = np.sum(matrix, axis=1).reshape(-1,1)
print("Сума елементів кожного рядка:")
print(row_sums)
#В результаті отримали вектор - стовпчик

Сума елементів кожного рядка:
[[ 4]
 [10]
 [ 9]]


9. Створити вектор, що містить 25 елементів. Заповнити числами від 0 до 9. Відсортувати числа за спаданням

In [13]:
vector = np.random.randint(0,10,size=25)
print("Початковий вектор:")
print(vector)

#Сортуємо числа за спаданням
sorted_vector = np.sort(vector)[::-1]

print("Вектор після сортування за спаданням:")
print(sorted_vector)

Початковий вектор:
[1 1 7 4 9 7 0 5 3 2 9 7 8 7 1 8 4 8 7 3 4 2 2 6 5]
Вектор після сортування за спаданням:
[9 9 8 8 8 7 7 7 7 7 6 5 5 4 4 4 3 3 2 2 2 1 1 1 0]


10.Знайти моду, медіану, середнє, максимальне, мінімальне значення

In [15]:
from scipy import stats
#Знаходимо моду
mode = stats.mode(vector)

#Знаходимо медіану
median = np.median(vector)

#Знаходимо середнє
mean = np.mean(vector)

#Знаходимо максимальне значення
max_value = np.max(vector)

#Знаходимо мінімальне значення
min_value = np.min(vector)

print("Мода:", mode)
print("Медіана:", median)
print("Середнє:", mean)
print("Максимальне значення:", max_value)
print("Мінімальне значення:", min_value)

Мода: ModeResult(mode=np.int64(7), count=np.int64(5))
Медіана: 5.0
Середнє: 4.8
Максимальне значення: 9
Мінімальне значення: 0


11. Створити дві матриці 4*4, заповнені числами від 1 до 10. Обчислити суму, різницю, поелементний добуток, частку

In [16]:
# Створюємо дві матриці 4х4 із випадкових цілих чисел від 1 до 10
matrix1  = np.random.randint(1,11, size=(4,4))
matrix2  = np.random.randint(1,11, size=(4,4))

print("Матриця 1:")
print(matrix1)

print("Матриця 2:")
print(matrix2)

Матриця 1:
[[6 1 6 3]
 [3 8 7 1]
 [7 7 5 7]
 [5 6 9 1]]
Матриця 2:
[[ 9  3  1  4]
 [ 1  8  9  7]
 [ 1  7  3  7]
 [ 8 10  6  7]]


In [17]:
#Обчислюємо суму матриць
matrix_sum = matrix1 + matrix2

#Обчислюємо різницю матриць
matrix_diff = matrix1 - matrix2

#Обчислюємо поелементний добуток матриць
matrix_product = matrix1 * matrix2

#Обчислюємо поелементну частку матриць
#Для запобігання ділення на нуль, використовуємо np.divide з параметром where
matrix_division = np.divide(matrix1, matrix2, where=(matrix2!=0))

print("\nСума матриць:")
print(matrix_sum)

print("\nРізниця матриць:")
print(matrix_diff)

print("\nПоелементний добуток матриць:")
print(matrix_product)

print("\nПоелементна частка матриць:")
print(matrix_division)


Сума матриць:
[[15  4  7  7]
 [ 4 16 16  8]
 [ 8 14  8 14]
 [13 16 15  8]]

Різниця матриць:
[[-3 -2  5 -1]
 [ 2  0 -2 -6]
 [ 6  0  2  0]
 [-3 -4  3 -6]]

Поелементний добуток матриць:
[[54  3  6 12]
 [ 3 64 63  7]
 [ 7 49 15 49]
 [40 60 54  7]]

Поелементна частка матриць:
[[0.66666667 0.33333333 6.         0.75      ]
 [3.         1.         0.77777778 0.14285714]
 [7.         1.         1.66666667 1.        ]
 [0.625      0.6        1.5        0.14285714]]


**Висновок:** У роботі були створені матриці та вектори, виконані основні операції над ними: обчислення визначника, суми, добутку, середнього, мінімального та максимального значень, а також статистичних характеристик (моди, медіани). Проведено арифметичні операції з матрицями.